#!/bin/bash
#SBATCH --job-name=DPORTF       # Job name
#SBATCH --nodes=1               # Run on a single CPU
#SBATCH --time=00:45:00         # Time limit hrs:min:sec
#SBATCH -p special


module purge
module load hwloc/2.7.0/gcc-7.3.0-73uz
module load blas/mkl/2017.4
module load openmpi/4.1.2/gcc-7.3.0-ixq7
module load cuda/11.6.0/gcc-7.3.0-cqym

mpirun -np 1 --mca btl_openib_allow_ib 1 --map-by ppr:1:node --bind-to numa /home/mannaparambil/dplasma/build/tests/testing_dpotrf -c $core -t 200 -N 20000 -P 1 -- --mca profile_filename $trace

